#Pinatas configuration file

#Should we use permission for each pinata?
using-permissions: true

#Notify about plugin updates?
update-notify: true

#In this worlds you can create pinata only by console or '/pinata create' admin command.
disabled-worlds:
- 'cASe SenSItIve wORLD namE'

#Exclusions of creating pinatas using crates or signs in disabled worlds
#false = blocked, true = unlocked
disabled-worlds-exclusions:
  crates: false
  signs: false

#Requires Holographic Displays
#Crate hologram refresh time.
#Warning! Do not set this value to big because destroying crate cause hologram update in this refresh time
#Time in seconds.
hologram-refresh: 2

#Crate particle refresh time.
#Time in seconds.
particle-refresh: 2

#Should player get blindness effect when pinata is created?
blindness-effect: false

#Enable full blindness effect? Blindness + night vision combination
#'blindness-effect' must be true!
full-blindness-effect: false

#Duration in seconds of blindness effect after pinata is created
#'blindness-effect' must be true!
blindness-duration: 10

#How many hearts should EVERY damage of pinata take?
#0.0 = disabled, 1 = 0.5 heart
#Useful if you're creating public types, players won't kill pinatas with their OP swords that fast.
damage-modifier: 0.0

#Because you can't set command item, you need to use configured item.
command-item: paper

#Because you can't set money item, you need to use configured item.
money-item: diamond

#Because you can't set gun item, you need to use configured item.
gun-item: iron_barding

#Enable halloween special pinata effects?
halloween-mode: false

File-Version-Do-Not-Edit: 4